apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-food-api
  labels:
    app: deployment-food-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: deployment-food-api
  template:
    metadata:
      labels:
        app: deployment-food-api
    spec:
      containers:
        - name: deployment-food-api
          image: jhonataneduardo/tech-challenge-api:v1
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 5000
      imagePullSecrets:
        - name: docker-registry-secret
