apiVersion: v1
kind: Service
metadata:
  name: service-tech-challenge-api
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  selector:
    app: deployment-tech-challenge-api
